### ISSUE TITLE
Incorrect info in metrics definitions

### ISSUE THREAD

**Issue by 0xSolus** [Tachikoma000/Olympus_Playground#14]
<img width="445" alt="2021-11-29_21-28-24" src="https://user-images.githubusercontent.com/94268527/143974928-eabf7220-625a-4dba-9ff3-c8ff12a750bd.png">

I've since come to understand that this is incorrect. Ohm held by the DAO is not part of circulating supply. See below:

<img width="592" alt="2021-11-29_21-31-02" src="https://user-images.githubusercontent.com/94268527/143975102-b6809051-1550-488f-9f54-92abf198d979.png">

**Comment by Tachikoma000** [comment]
> <img alt="2021-11-29_21-28-24" width="445" src="https://user-images.githubusercontent.com/94268527/143974928-eabf7220-625a-4dba-9ff3-c8ff12a750bd.png">
> 
> I've since come to understand that this is incorrect. Ohm held by the DAO is not part of circulating supply. See below:
> 
> <img alt="2021-11-29_21-31-02" width="592" src="https://user-images.githubusercontent.com/94268527/143975102-b6809051-1550-488f-9f54-92abf198d979.png">

Oh wow, I did not know this . Thanks for sending this clarification
