### ISSUE TITLE
TotalSupply may be stagnant

### ISSUE THREAD

**Issue by 0xSolus** [Tachikoma000/Olympus_Playground#24]
_Reported Bug_ _Investigate_
This may be an issue with data delay, or with V2 migration.  

---

<img width="694" alt="2021-12-13_23-14-29" src="https://user-images.githubusercontent.com/94268527/145931968-de7471a5-91ea-49aa-ad31-6f318dc7e5cb.png">

**Comment by 0xSolus** [comment]
It looks like the total supply of Ohm is no longer growing. I'm not familiar enough with V2 to understand if this is temporary, or if this is just how it works now. However, I suspect that the subgraph just needs to be updated for V2.

If the total supply will no longer be growing, we should consider not using this as a default metric for the Explorer page. I think we should still leave it as a possible metric for posterity though. 

<img width="1284" alt="2021-12-14_00-39-57" src="https://user-images.githubusercontent.com/94268527/145939851-e7a070a0-c545-4e67-9e46-3b9bb1c1bcf1.png">

**Comment by Tachikoma000** [comment]
This issue has been resolved.
The reasons for the discrepancies were:
1. Using outdate graph query api
2. V2 migration affecting data sources

To fix this, we simply had to update the query url
